### ISSUE TITLE
Improve code readability

### ISSUE THREAD

**Issue by AlexWaygood** [PyCQA/flake8-pyi#63]
I'd like to make several changes to `pyi.py` to improve code readability. These are all quite small changes, but I'll submit them as separate PRs, to make them easier to review:

1. [X] Use the class-based syntax for the `Error` namedtuple: #65
2. [X] Reduce the use of unnecessary abbreviations in the code: #66
3. [X] `PyiVisitor._in_class` is quite poorly named: it sounds like it's a boolean value from the name, but it's actually an integer that tells you the level of class nesting the visitor is in: #64
4. [X] I'd like to make several small changes to increase the readability of the control flow: #67 

Additional changes I'd like to see:

~~I also like [the new `@attrs.define` API](https://hynek.me/articles/import-attrs/)  _much_ more than the legacy API. I'd quite like to refactor `pyi.py` to use the newer API; however, that would mean we'd have to pin `attrs` to `>=21.3.0`. Thoughts on that?~~ 

- [X] ^Let's just use dataclasses and drop support for 3.6, as discussed below: #78
- [ ] Maybe it would be nice to increase the number of docstrings and reduce the number of comments.

**Comment by JelleZijlstra** [comment]
> I also like the new @attrs.define API much more than the legacy API. I'd quite like to refactor pyi.py to use the newer API; however, that would mean we'd have to pin attrs to >=21.3.0. Thoughts on that?

I'd suggest just using dataclasses (stdlib in 3.7+ and the backport in 3.6).

**Comment by AlexWaygood** [comment]
> I'd suggest just using dataclasses (stdlib in 3.7+ and the backport in 3.6).

Given 3.6 is EOL, we could also just drop support for 3.6 and unconditionally use stdlib dataclasses.

**Comment by AlexWaygood** [comment]
I'm not sure improving docstrings is feasible or desirable at the moment, given how quickly the code's been changing over the last few days! So I'll close this as "fixed". We can always come back to improving the docstring/comment situation at a later date if we want to.
